[tools]
rojo = "rojo-rbx/rojo@7.5.1"
selene = "Kampfkarren/selene@0.29.0"
stylua = "JohnnyMorganz/StyLua@0.20.0"
rbxcloud = "Sleitnick/rbxcloud@0.14.0"
wally = "upliftgames/wally@0.3.2"
lune = "lune-org/lune@0.10.3"
