name: CI

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
    paths:
      - "src/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Styling
        uses: ./.github/actions/style
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linting
        uses: ./.github/actions/lint
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tests
        uses: ./.github/actions/tests
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROBLOX_TEST_API_KEY: ${{ secrets.ROBLOX_TEST_API_KEY }}